//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrabBimestral.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int Usu_ID { get; set; }
        public string Usu_Email { get; set; }
        public string Usu_Senha { get; set; }
        public bool Usu_Admin { get; set; }
    }
}
