//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrabBimestral.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendaProduto
    {
        public int VeP_ID { get; set; }
        public int ID_Venda { get; set; }
        public int ID_Produto { get; set; }
        public int VeP_Qtd { get; set; }
        public decimal VeP_PrecoVenda { get; set; }
    
        public virtual Venda Venda { get; set; }
        public virtual Produto Produto { get; set; }
    }
}
